[package]
name = "directory_entries_llm"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25.5"
kalosm = { version = "0.4.0", features = ["language", "metal", "vision"] }
tokio = { version = "1.44.0", features = ["full"] }
