[package]
name = "directory_entries_llm"
version = "0.1.0"
edition = "2024"

[dependencies]
kalosm = { version = "0.4.0", features = ["language", "metal"] }
tokio = { version = "1.44.0", features = ["full"] }
